### ISSUE TITLE
Nitro generator bug

### ISSUE THREAD

**Issue by Troupote** [Xvirus-Team/Xvirus-Tools#31]
**Describe the bug**
When started, the generator crash immediately 

**To Reproduce**
1. go on the main menu
2. Type the nitro generator code 
3. Press enter

**Expected behavior**
I expected it to be a screen where a lot of code are written on the windows

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Version 1.6.5

**Comment by optimus10ro** [comment]
It's broken, has a astronomical chance of working anyway
