### ISSUE TITLE
What is token?

### ISSUE THREAD

**Issue by Dominik919-alt** [Xvirus-Team/Xvirus-Tools#34]
When i wanna do something like delete account it wants a token. How do i get the token?

**To Reproduce**
1. Go to the launcher
2. Click on anything [ something is buged ]
3. It says : Token :

**Comment by cocorico8** [comment]
you need to token grab someone ( with is approbation of course )

**Comment by MyLifeIsSakura** [comment]
Dude, before using these tools do some research
