### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gewoonhacker123** [Xvirus-Team/Xvirus-Tools#38]
![image](https://github.com/Xvirus-Team/Xvirus-Tools/assets/140543036/ce811dc6-7dc3-41ad-a1aa-e54bb3050bc5)
Help error

**Comment by BurgerBoy76** [comment]
cd C:\Users\Users\Desktop\Xvirus-Tools-main 
pip install -r requirements.py run that in cmd prompt
