### ISSUE TITLE
virus?

### ISSUE THREAD

**Issue by Chicogoes** [Xvirus-Team/Xvirus-Tools#39]
Is it a virus?

**Comment by BurgerBoy76** [comment]
it is litterally written in python, one of the easiest launguages to learn/read. try looking yourself.

**Comment by labla124** [comment]
For those who does not understand python because being new to it, you figured it out ?

**Comment by AltepFrance** [comment]
yup kaspersky detect it has a virus

**Comment by DXVVAY** [comment]
ITS FUCKING OPEN SOURCE JUST READ HJE FUCKING CODE YOU RETARDS

**Comment by Chicogoes** [comment]
It’s not a virus.
