### ISSUE TITLE
SKID DETECTED

### ISSUE THREAD

**Issue by gumbobr0t** [Xvirus-Team/Xvirus-Tools#47]
**Expected behavior**
a program that is not fully skidded from hazard nuker
**Screenshots**
https://imgflip.com/i/7x0h2z

**Desktop:**
 - OS: anti skid os
 - skidding is bad Browser 
 - Version don't skid ultimate

**Additional context**
you are a stupid skid

**Comment by DXVVAY** [comment]
100%

this is defo skidded

**Comment by gumbobr0t** [comment]
stfu we both know that this is completely skidded 

hmm weird that your files and the hazard files have the exact same names hmmm
https://i.imgur.com/DqTQ5ec.png
https://i.imgur.com/6GGE3Ve.png

also weird that you use the same code:
https://i.imgur.com/F6ZdeVi.png
https://i.imgur.com/AnYbvCV.png

now tell me fucking again that you did not skid this 🤡
