### ISSUE TITLE
skiddin's a sin

### ISSUE THREAD

**Issue by gumbobr0t** [Xvirus-Team/Xvirus-Tools#48]
### [gumbobr0t](https://github.com/gumbobr0t) commented [4 hours ago](https://github.com/Xvirus-Team/Xvirus-Tools/issues/47#issue-1867987118) • 
**Expected behavior**
a program that is not fully skidded from hazard nuker
**Screenshots**
https://imgflip.com/i/7x0h2z

**Desktop:**
 - OS: anti skid os
 - skidding is bad Browser 
 - Version don't skid ultimate

**Additional context**
you are a stupid skid

--------------------------------------------------

### [DXVVAY](https://github.com/DXVVAY) commented [1 hour ago](https://github.com/Xvirus-Team/Xvirus-Tools/issues/47#issuecomment-1694327274) | this just approves that he is not only a skid, he is a STUPID skid
100%

this is defo skidded

--------------------------------------------------

### [gumbobr0t](https://github.com/gumbobr0t) commented [2 minutes ago](https://github.com/Xvirus-Team/Xvirus-Tools/issues/47#issuecomment-1694336411)
stfu we both know that this is completely skidded

hmm weird that your files and the hazard files have the exact same names hmmm
https://i.imgur.com/DqTQ5ec.png
https://i.imgur.com/6GGE3Ve.png

also weird that you use the same code:
https://i.imgur.com/F6ZdeVi.png
https://i.imgur.com/AnYbvCV.png

now tell me fucking again that you did not skid this 🤡

**Comment by DXVVAY** [comment]
Again... bruh
